With all the star power of Jennifer Lawrence, Chris Pratt, Laurence Fishburne, and even Michael Sheen, one might expect this movie to set the box office on fire. No doubt that was the studio bosses’ plan. Sadly, it was not to be. Stiff competition and mixed reviews meant that Passengers ended up only just achieving a passing result commercially.

So, what was it about this movie that led to its at-best mild reception? It had a strong, experienced, successful, and well-known cast. Visually, it was suitably stunning with use of all the right technical mod-cons. Yet, somehow, this movie divided audiences and critics alike. Could it have been the story itself? Let us consider that.

As I will not assume that you have seen the movie, Sweet T., I will try to tread as carefully as possible, seeking to not reveal too much, save for this one fair warning: even as I try to obscure specifics, you may still infer more than you’d like to know before watching.

From the opening credits, it is apparent that this film will be ethereal. The opening overture of tubular bells meets whale song quietly screams mysterious, other-worldly. The initial vista of the galactic disk depicts the vastness of the setting, only to have our focus brought to bear upon the seemingly diminutive hull of a spaceship silently emerging out of the infinite fog of distant stars.

We are then invited into the picture: not a diminutive spaceship, a colossal construction spiralling through the cosmos. No time is wasted revealing that this transport has an upcoming date with destiny. So, the story begins.

The idea of being stranded alone is far from new. From Robinson Crusoe to Cast Away, the premise has made for ample film fodder. Even being lost in space is not entirely unique, yet here, the Infinite is nothing more than an ocean to be crossed. The real story happens inside the ship, the Avalon.

Movies like this always bring to the front of one’s mind the same question: what would I do? How would I react? Would I still be able to discern what was right, and would I even choose it in the face of that future? Movies let us look through such windows without having to live in such turmoil. And of course, a good story needs drama. What better drama can there be than to have your hero fall, to fail, to not uphold the highest standards even when facing a nightmare scenario.

True to our writer’s handbook, our hero succumbs to the temptation placed before him: a veritable buffet from which to make his selection and an aeon in which the idea can gnaw upon his diminishing sanity. The outcome was all but inevitable. Yet, in the process, the one person upon whom we hope we can rely becomes the monster we all pray we never have to resist. Through his transgression, our hero commits a crime that does not even have a name. It is life-path theft, existential kidnapping, future imprisonment, “temporicide”.

Who falls foul of this nameless crime? One Ms. Aurora Lane! Aurora – The Light that fills the Darkness. Lane – the narrow road, the road less travelled by, This Path by another name. Just a reminder, Precious Persephone, I did not write this! Her life forever altered by the travesty committed upon her. Without consent, whilst disempowered, all she had planned was stolen. For many, the loss and lack of Aurora’s agency within the story is as much a crime.

Our two protagonists struggle separately and then together, first to find a solution, and then to overcome the boredom, playing as a means of distraction, avoiding the need to ever accept the situation, one living as if in a fantasy, the other living a lie. I’ll let you decide who is who. Yet, all the while, we, the all-seeing observers know – there are shoes that must fall.

Through a careless word, a mistimed absence, and an indiscreet accident, the hidden, horrible truth is discovered. The monster is revealed. As you can imagine, with no one else present, the victim has free rein to become judge, jury, and almost executioner. For many, though, even the retribution extracted was far from sufficient, which then begs the question: what would be enough?

With no options for absolution or reconciliation, we see how the only path left is finally taken by both of our passengers, to get on with living, that is until the other shoe falls, until the unknown circumstances finally collapse in upon them, requiring their full, focused, co-operative attention…and the short-lived assistance of Gus, their resident expert authority figure.

As the precarious nature of their position becomes fully apparent, circumstances force the two to realise who they must be in themselves, for the other, and collectively together. Again, the popular lines from Storyteller’s Guidebook come into play: the Test – the Hero’s Redemption. Like all good fairytales, especially in predictable Hollywood, despite nothing being as they planned, even despite the option to return to the past, they remember to make the most of where they are and “they all lived happily ever after”.

A lovely tale to be sure – somewhere between The Blue Lagoon and Titanic, with a sugary ending to please the populace, only it did not. No Macbethian retribution for evils perpetrated by our hero. No catastrophic collapse to be survived by our surviving solo heroine. So, how is it that this slightly successful story makes it to the Movie List of This?

In a story with so few characters and locations, the messages, meanings, and lessons of every moment, of every word, of every scene come thick and fast in a multilayered array of perception. From the infinite, inhospitable stars beyond the ship to the perceived safety of a self-contained sleep chamber, what this movie has to say to us, to anyone, depends as much on what we bring to it as it does on the action on the screen.

So let us start from the outside and work our way in: we all know the sky above - the stars, the planets, the galactic plane. More than any time before, we have our imaginings of space – it is vast, mostly dark, unfriendly to our everyday life, yet it is exactly this cradle in which we all live. Perhaps that is why so many of us find it so easy to sit outside on a clear, dark night to consider from the safety of our own little world, the infinite darkness of the distant firmament above. How much does the division between the Heavens and the Earth mirror our own internal divide between the waking self we think we know and the crazy confusion of the chaotic subconscious within which we unconsciously all exist? Is that why stories of being lost in the outer worlds have so long appealed to the human psyche?

Which brings us to the stage upon which our tale is told: the ship passing through the night – the Avalon. For our protagonists, it is everything, all the world, the vessel which carries them through life. Inside is safe, known, controlled. Outside lives risk, danger, death, the unknowable, uncontrollable world of the wild. Here the multilayering of the metaphors begins to hit home: is the Avalon us and our carefully constructed lives drifting through a cruel, indifferent world, or is it our own conscious selves struggling to create a cogent, self-contained reality within the broader universe of ideas? And what happens when, as they inevitably do, the extremes of these two dualities do eventually collide?

Obviously, there is little point having a ship if there is no one in it. Whilst it is true that we do not have many, who they are for us ends up being quite remarkable. Our hero, fallen and redeemed…maybe, is an every-man, an engineer of all things (we’ll forgive the mechanical part – no one is perfect!), a solver of problems, a maker of worlds, not the teller of stories, the doer of them. Our heroine, captivating, intriguing, intelligent, worldly, and well spoken. Without trying, just by being, she captures the beast. She has stories and the capacity to tell them. With her vision firmly fixed on horizons well beyond, she dreams of an unobtainable timelessness for her words.

Then, there is Gus, an expert in the ways of the strange world in which they all live. His part within the story is short-lived yet in his authoritative presence, he personifies change of the world view. And why is this so remarkable? Perhaps you remember my story, Beautiful Girl? Do you remember how I came to be in your world? Within the UQ Chemical Engineering department, the co-ordinator of the student exchange programme was a gentleman by the name of none other than Gus, the man who legitimised my own change of world view. 

There are other players within the story. They do not necessarily appear within the film, yet their influence is crucial to its execution. If the Avalon is the world in which we live, then the Homestead Company is the agent activating that world, the processes that make it go, and just as the world has its limits, so does the Homestead Company. Their system has its design. The desired outcomes of that design differ depending on who is considering them: for the passengers, it is a planet; for the company, it is a profit; those two prizes sometimes end up being at odds both with each other, and with the chaotic universe through which they all travel. It is at that boundary, that battery limit of spatial, corporate responsibility that the pointed edge of that chaotic universe was able to break through; impacting upon the quiet world within; changing the status quo; altering the course, imperceptibly at first, of everyone. With one random act, the universe, without thought or care, changes everything.

I am sure, if you have read this far, Andromeda Adored, you will undoubtedly see the parallels between the Passengers upon the Avalon and our own parallel transits of this complicated, at times chaotic world. Drifting as I was to who knows where when we reconnected, your steadying hand captured my distant tether. Yet, whilst maintaining a stable orbit closer than either of us believed possible, I have sought to ensure that no temporicide is committed. It is not I who seeks to bend another’s universe to my will. I neither want to constrain nor control you within your world, nor do I wish to slam into the ship of another’s life. Yet, even at this great distance, even after all this time, there is less doubt in my mind, within my heart, than at any time ever before, about the continuing correlation of the Wavefunction of Love that is shared. I remain forever, willingly entangled within The Red Thread that has always been between us, the one we discovered all those years ago.

[← Back to Red Thread Film Notebook index](./index.html)

