export const STORAGE_KEY = 'tc-v3-data';
export const TIMER_KEY = 'tc-v3-active-timer';
export const LEGACY_STORAGE_KEYS = ['tc-v2-data'];

export const DEFAULT_USERS = [
  {
    id: 'peter',
    label: 'Peter',
    shortLabel: 'P',
    active: true,
    heightCm: null,
    preferredWeightUnit: 'kg',
    dailyStepTarget: null
  },
  {
    id: 'louise',
    label: 'Louise',
    shortLabel: 'L',
    active: false,
    heightCm: null,
    preferredWeightUnit: 'kg',
    dailyStepTarget: null
  }
];

export const EXERCISE_CATALOG = [
  { id: 'push-ups', name: 'Push-ups', category: 'strength', muscles: 'chest, front shoulders, triceps, core', notes: 'Bodyweight push', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'incline-push-ups', name: 'Incline push-ups', category: 'strength', muscles: 'chest, shoulders, triceps, core', notes: 'Easier version', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'front-raises', name: 'Front raises', category: 'strength', muscles: 'front shoulders', notes: '1 to 3 kg', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'lateral-raises', name: 'Lateral raises', category: 'strength', muscles: 'side shoulders', notes: '1 to 3 kg', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'scaption-raises', name: 'Scaption raises', category: 'rehab', muscles: 'shoulder complex, especially deltoid / supraspinatus area', notes: 'Light and controlled', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'bent-over-dumbbell-row', name: 'Bent-over dumbbell row', category: 'strength', muscles: 'upper back, lats, rear shoulders, biceps, trunk stabilisers', notes: 'Strong inclusion', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'single-arm-dumbbell-row', name: 'Single-arm dumbbell row', category: 'strength', muscles: 'lats, rhomboids, rear shoulder, biceps, core', notes: 'Often easier to control than both arms at once', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'reverse-fly', name: 'Reverse fly / rear delt raise', category: 'strength', muscles: 'rear shoulders, upper back', notes: 'Use the lightest weights', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'squats', name: 'Squats', category: 'strength', muscles: 'quads, glutes, adductors, core', notes: 'Bodyweight or goblet style', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'goblet-squats', name: 'Goblet squats', category: 'strength', muscles: 'quads, glutes, core', notes: 'Hold one dumbbell at chest', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'reverse-lunges', name: 'Reverse lunges', category: 'strength', muscles: 'quads, glutes, hamstrings, calves', notes: 'Start bodyweight', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'step-ups', name: 'Step-ups', category: 'strength', muscles: 'quads, glutes, calves', notes: 'Use a step or stair', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'glute-bridges', name: 'Glute bridges', category: 'strength', muscles: 'glutes, hamstrings, lower back', notes: 'Can later rest a dumbbell on hips', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'calf-raises', name: 'Calf raises', category: 'strength', muscles: 'calves', notes: 'Hold dumbbells if needed', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'forward-leg-lifts', name: 'Forward leg lifts', category: 'mobility', muscles: 'hip flexors, quads, lower abs', notes: 'Better as bodyweight', supportsDuration: false, favourite: true, detailProfile: 'standard' },
  { id: 'lateral-leg-lifts', name: 'Lateral leg lifts', category: 'mobility', muscles: 'glute medius / minimus, outer hip', notes: 'Bodyweight is fine', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'front-plank', name: 'Front plank', category: 'core', muscles: 'deep core, abs, shoulders, glutes', notes: 'Bodyweight', supportsDuration: true, favourite: true, detailProfile: 'standard' },
  { id: 'side-plank', name: 'Side plank', category: 'core', muscles: 'obliques, lateral core, shoulder, glute medius', notes: 'Bodyweight', supportsDuration: true, favourite: false, detailProfile: 'standard' },
  { id: 'bird-dog', name: 'Bird-dog', category: 'core', muscles: 'deep core, glutes, lower back, shoulder stabilisers', notes: 'Very good spine-friendly core work', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'dead-bug', name: 'Dead bug', category: 'core', muscles: 'deep core, trunk control', notes: 'Good alternative to crunches', supportsDuration: false, favourite: false, detailProfile: 'standard' },
  { id: 'superman', name: 'Superman / back extension hold', category: 'core', muscles: 'lower back, glutes, upper back', notes: 'Light, controlled', supportsDuration: true, favourite: false, detailProfile: 'standard' },
  { id: 'concept2-rower', name: 'Concept2 rower', category: 'cardio', muscles: 'legs, hips, back, arms, aerobic conditioning', notes: 'Cardio plus whole-body work', supportsDuration: true, favourite: true, detailProfile: 'rowing' },
  { id: 'exercise-bike', name: 'Exercise bike', category: 'cardio', muscles: 'legs, hips, aerobic conditioning', notes: 'Bike-specific cardio fields available', supportsDuration: true, favourite: true, detailProfile: 'bike' },
  { id: 'cycling', name: 'Cycling', category: 'cardio', muscles: 'legs, hips, aerobic conditioning', notes: 'Outdoor or general cycling session', supportsDuration: true, favourite: false, detailProfile: 'bike' },
  { id: 'walking', name: 'Walking', category: 'cardio', muscles: 'legs, hips, aerobic conditioning', notes: 'Walking-specific metrics available', supportsDuration: true, favourite: false, detailProfile: 'walking' },
  { id: 'treadmill', name: 'Treadmill', category: 'cardio', muscles: 'legs, hips, aerobic conditioning', notes: 'Walking or treadmill-specific metrics available', supportsDuration: true, favourite: false, detailProfile: 'walking' }
];

export const STARTER_DATA = {
  schemaVersion: 3,
  config: {
    currentUserId: 'peter'
  },
  users: DEFAULT_USERS,
  exerciseCatalog: EXERCISE_CATALOG,
  exerciseEntries: [
    {
      id: 'ex-20260324-front',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260324-lateral',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260324-scaption',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: 'Muscle discomfort only.'
    },
    {
      id: 'ex-20260324-pushups',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'push-ups',
      exerciseName: 'Push ups',
      category: 'strength',
      sets: 1,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'moderate',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260324-leglifts',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'forward-leg-lifts',
      exerciseName: 'Forward leg lifts',
      category: 'mobility',
      sets: null,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260324-calf',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'calf-raises',
      exerciseName: 'Calf raises',
      category: 'strength',
      sets: null,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260325-front',
      date: '2026-03-25',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260325-lateral',
      date: '2026-03-25',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260325-scaption',
      date: '2026-03-25',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260326-front',
      date: '2026-03-26',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260326-lateral',
      date: '2026-03-26',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260326-scaption',
      date: '2026-03-26',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    },
    {
      id: 'ex-20260326-squats',
      date: '2026-03-26',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'squats',
      exerciseName: 'Squats',
      category: 'strength',
      sets: 1,
      reps: 25,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'moderate',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: '3 kg per arm to overhead lift.'
    },
    {
      id: 'ex-20260326-row',
      date: '2026-03-26',
      recordTime: '',
      userId: 'peter',
      exerciseId: 'bent-over-dumbbell-row',
      exerciseName: 'Bent Over Rowing',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationSec: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      avgHr: null,
      maxHr: null,
      workoutCalories: null,
      avgSpeedKmh: null,
      steps: null,
      avgCadence: null,
      avgPace500: '',
      avgStrokeRate: null,
      avgPower: null,
      notes: ''
    }
  ],
  metricEntries: [
    {
      id: 'metric-20260323-weight',
      date: '2026-03-23',
      recordTime: '',
      userId: 'peter',
      bodyWeight: 86.9,
      bodyWeightUnit: 'kg',
      systolic: null,
      diastolic: null,
      pulseBpm: null,
      sleepHours: null,
      energy: '',
      soreness: '',
      steps: null,
      notes: 'Measured on home scales which may be weighing about 1 to 1.5 kg light.'
    }
  ],
  noteEntries: [
    {
      id: 'note-20260324-shoulder',
      date: '2026-03-24',
      recordTime: '',
      userId: 'peter',
      title: 'Shoulder response',
      body: 'Left shoulder felt good after the session. Good starting point level.'
    }
  ]
};
