export const STARTER_DATA = {
  users: [
    { id: 'martin', name: 'Martin', active: true },
    { id: 'tamara', name: 'Tamara', active: false }
  ],
  exerciseCatalog: [
    { id: 'push-ups', name: 'Push-ups', category: 'strength', muscles: 'chest, front shoulders, triceps, core', canUseDumbbells: false, notes: 'Bodyweight push' },
    { id: 'incline-push-ups', name: 'Incline push-ups', category: 'strength', muscles: 'chest, shoulders, triceps, core', canUseDumbbells: false, notes: 'Easier version' },
    { id: 'front-raises', name: 'Front raises', category: 'strength', muscles: 'front shoulders', canUseDumbbells: true, notes: '1 to 3 kg' },
    { id: 'lateral-raises', name: 'Lateral raises', category: 'strength', muscles: 'side shoulders', canUseDumbbells: true, notes: '1 to 3 kg' },
    { id: 'scaption-raises', name: 'Scaption raises', category: 'rehab', muscles: 'shoulder complex, especially deltoid / supraspinatus area', canUseDumbbells: true, notes: 'Light and controlled' },
    { id: 'bent-over-dumbbell-row', name: 'Bent-over dumbbell row', category: 'strength', muscles: 'upper back, lats, rear shoulders, biceps, trunk stabilisers', canUseDumbbells: true, notes: 'Strong inclusion' },
    { id: 'single-arm-dumbbell-row', name: 'Single-arm dumbbell row', category: 'strength', muscles: 'lats, rhomboids, rear shoulder, biceps, core', canUseDumbbells: true, notes: 'Often easier to control than both arms at once' },
    { id: 'reverse-fly', name: 'Reverse fly / rear delt raise', category: 'strength', muscles: 'rear shoulders, upper back', canUseDumbbells: true, notes: 'Use the lightest weights' },
    { id: 'squats', name: 'Squats', category: 'strength', muscles: 'quads, glutes, adductors, core', canUseDumbbells: true, notes: 'Bodyweight or goblet style' },
    { id: 'goblet-squats', name: 'Goblet squats', category: 'strength', muscles: 'quads, glutes, core', canUseDumbbells: true, notes: 'Hold one dumbbell at chest' },
    { id: 'reverse-lunges', name: 'Reverse lunges', category: 'strength', muscles: 'quads, glutes, hamstrings, calves', canUseDumbbells: true, notes: 'Start bodyweight' },
    { id: 'step-ups', name: 'Step-ups', category: 'strength', muscles: 'quads, glutes, calves', canUseDumbbells: true, notes: 'Use a step or stair' },
    { id: 'glute-bridges', name: 'Glute bridges', category: 'strength', muscles: 'glutes, hamstrings, lower back', canUseDumbbells: true, notes: 'Can later rest a dumbbell on hips' },
    { id: 'calf-raises', name: 'Calf raises', category: 'strength', muscles: 'calves', canUseDumbbells: true, notes: 'Hold dumbbells if needed' },
    { id: 'forward-leg-lifts', name: 'Forward leg lifts', category: 'mobility', muscles: 'hip flexors, quads, lower abs', canUseDumbbells: false, notes: 'Better as bodyweight' },
    { id: 'lateral-leg-lifts', name: 'Lateral leg lifts', category: 'mobility', muscles: 'glute medius / minimus, outer hip', canUseDumbbells: false, notes: 'Bodyweight is fine' },
    { id: 'front-plank', name: 'Front plank', category: 'core', muscles: 'deep core, abs, shoulders, glutes', canUseDumbbells: false, notes: 'Bodyweight' },
    { id: 'side-plank', name: 'Side plank', category: 'core', muscles: 'obliques, lateral core, shoulder, glute medius', canUseDumbbells: false, notes: 'Bodyweight' },
    { id: 'bird-dog', name: 'Bird-dog', category: 'core', muscles: 'deep core, glutes, lower back, shoulder stabilisers', canUseDumbbells: false, notes: 'Very good spine-friendly core work' },
    { id: 'dead-bug', name: 'Dead bug', category: 'core', muscles: 'deep core, trunk control', canUseDumbbells: false, notes: 'Good alternative to crunches' },
    { id: 'superman', name: 'Superman / back extension hold', category: 'core', muscles: 'lower back, glutes, upper back', canUseDumbbells: false, notes: 'Light, controlled' },
    { id: 'concept2-rower', name: 'Concept2 rower', category: 'cardio', muscles: 'legs, hips, back, arms, aerobic conditioning', canUseDumbbells: false, notes: 'Cardio plus whole-body work' },
    { id: 'exercise-bike', name: 'Exercise bike', category: 'cardio', muscles: 'legs, hips, aerobic conditioning', canUseDumbbells: false, notes: 'Cardio' }
  ],
  exerciseEntries: [
    {
      id: 'ex-20260324-front',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260324-lateral',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260324-scaption',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: 'Muscle discomfort only.'
    },
    {
      id: 'ex-20260324-pushups',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'push-ups',
      exerciseName: 'Push ups',
      category: 'strength',
      sets: 1,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'moderate',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260324-leglifts',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'forward-leg-lifts',
      exerciseName: 'Forward leg lifts',
      category: 'mobility',
      sets: null,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260324-calf',
      date: '2026-03-24',
      userId: 'martin',
      exerciseId: 'calf-raises',
      exerciseName: 'Calf raises',
      category: 'strength',
      sets: null,
      reps: 20,
      weight: null,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: '',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260325-front',
      date: '2026-03-25',
      userId: 'martin',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260325-lateral',
      date: '2026-03-25',
      userId: 'martin',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260325-scaption',
      date: '2026-03-25',
      userId: 'martin',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260326-front',
      date: '2026-03-26',
      userId: 'martin',
      exerciseId: 'front-raises',
      exerciseName: 'Front arm raises',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260326-lateral',
      date: '2026-03-26',
      userId: 'martin',
      exerciseId: 'lateral-raises',
      exerciseName: 'Lateral arm raises',
      category: 'strength',
      sets: 2,
      reps: 20,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260326-scaption',
      date: '2026-03-26',
      userId: 'martin',
      exerciseId: 'scaption-raises',
      exerciseName: 'Scaption arm raises',
      category: 'rehab',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    },
    {
      id: 'ex-20260326-squats',
      date: '2026-03-26',
      userId: 'martin',
      exerciseId: 'squats',
      exerciseName: 'Squats',
      category: 'strength',
      sets: 1,
      reps: 25,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: 'Overhead lift',
      side: 'both',
      effort: 'moderate',
      jointPain: 'no',
      notes: '3 kg per arm to overhead lift.'
    },
    {
      id: 'ex-20260326-row',
      date: '2026-03-26',
      userId: 'martin',
      exerciseId: 'bent-over-dumbbell-row',
      exerciseName: 'Bent Over Rowing',
      category: 'strength',
      sets: 1,
      reps: 10,
      weight: 3,
      weightUnit: 'kg',
      durationMin: null,
      distanceKm: null,
      resistance: '',
      side: 'both',
      effort: 'steady',
      jointPain: 'no',
      notes: ''
    }
  ],
  metricEntries: [],
  noteEntries: []
};
